# Generated by Django 4.1.2 on 2022-10-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.TextField()),
                ('membername', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='comic',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
